// <auto-generated />
using System;
using CompraProgramada.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraProgramada.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302014714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaRecomendacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativa");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_desativacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("cestas_recomendacao");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_adesao");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_saida");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nome");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_mensal");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ContaGrafica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_conta");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("contas_graficas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroConta = "MST-000001",
                            Tipo = "Master"
                        });
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Cotacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("date")
                        .HasColumnName("data_pregao");

                    b.Property<decimal>("PrecoAbertura")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("preco_abertura");

                    b.Property<decimal>("PrecoFechamento")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("preco_fechamento");

                    b.Property<decimal>("PrecoMaximo")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("preco_maximo");

                    b.Property<decimal>("PrecoMinimo")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("preco_minimo");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "DataPregao")
                        .IsUnique();

                    b.ToTable("cotacoes");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Custodia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint")
                        .HasColumnName("conta_grafica_id");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_ultima_atualizacao");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("preco_medio");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId", "Ticker")
                        .IsUnique();

                    b.ToTable("custodias");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Distribuicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustodiaFilhoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("custodia_filhote_id");

                    b.Property<DateTime>("DataDistribuicao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_distribuicao");

                    b.Property<long>("OrdemCompraId")
                        .HasColumnType("bigint")
                        .HasColumnName("ordem_compra_id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("distribuicoes");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.EventoIR", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_evento");

                    b.Property<bool>("PublicadoKafka")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("publicado_kafka");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_base");

                    b.Property<decimal>("ValorIR")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_ir");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("eventos_ir");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ItemCesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CestaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cesta_id");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentual");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.HasIndex("CestaId");

                    b.ToTable("itens_cesta");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaMasterId")
                        .HasColumnType("bigint")
                        .HasColumnName("conta_master_id");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_execucao");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ticker");

                    b.Property<string>("TipoMercado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("tipo_mercado");

                    b.HasKey("Id");

                    b.HasIndex("ContaMasterId");

                    b.ToTable("ordens_compra");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Rebalanceamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataRebalanceamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_rebalanceamento");

                    b.Property<int>("QuantidadeComprada")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_comprada");

                    b.Property<int>("QuantidadeVendida")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_vendida");

                    b.Property<string>("TickerComprado")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ticker_comprado");

                    b.Property<string>("TickerVendido")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ticker_vendido");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_venda");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("rebalanceamentos");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ContaGrafica", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Cliente", "Cliente")
                        .WithOne("ContaGrafica")
                        .HasForeignKey("CompraProgramada.Domain.Entities.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Custodia", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.ContaGrafica", "ContaGrafica")
                        .WithMany("Custodias")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Distribuicao", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.OrdemCompra", "OrdemCompra")
                        .WithMany("Distribuicoes")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.EventoIR", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ItemCesta", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.CestaRecomendacao", "Cesta")
                        .WithMany("Itens")
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cesta");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.ContaGrafica", "ContaGrafica")
                        .WithMany()
                        .HasForeignKey("ContaMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Rebalanceamento", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaRecomendacao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ContaGrafica", b =>
                {
                    b.Navigation("Custodias");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.Navigation("Distribuicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
